// D3D12 resource creation and state tracking.
//
// Creates committed resources in the right heap for their classification, and
// tracks the resource state each one is currently in so that barriers can be
// generated by comparing against the state a use requires.
//
// Getting a barrier wrong is not reported at runtime outside the debug layer:
// a missing one yields undefined contents, and a wrong one can have the GPU
// reading memory while it is being written. Barriers are batched and submitted
// together rather than issued individually, since each one is a pipeline stall.
//
// Initial state must be recorded as the state D3D12 actually creates the
// resource in, not the state that was requested. Those differ for several heap
// types, and assuming the requested one desynchronises the tracking from the
// first use onward.

#define WIN32_LEAN_AND_MEAN
#define NOMINMAX
#include <windows.h>

#include <core/Resource12.h>
#include <core/DeviceContext12.h>
#include <core/Log.h>

#include <algorithm>
#include <cstring>

namespace mwon12 {

Placement12 ClassifyPlacement(D3DPOOL pool, DWORD usage, bool isBuffer) noexcept
{
    switch (pool) {
    case D3DPOOL_SYSTEMMEM:
    case D3DPOOL_SCRATCH:
        return Placement12::CpuOnly;

    case D3DPOOL_MANAGED:

        return Placement12::GpuShadowed;

    case D3DPOOL_DEFAULT:
    default:
        if (usage & D3DUSAGE_DYNAMIC) {

            return isBuffer ? Placement12::UploadHeap : Placement12::GpuShadowed;
        }
        return Placement12::GpuOnly;
    }
}

HRESULT Resource12::Init(DeviceContext12* ctx,
                         const D3D12_RESOURCE_DESC& desc,
                         D3D12_HEAP_TYPE heapType,
                         D3D12_RESOURCE_STATES initState,
                         const D3D12_CLEAR_VALUE* optClear,
                         const wchar_t* debugName) noexcept
{
    if (!ctx || !ctx->Device()) return E_INVALIDARG;
    m_ctx      = ctx;
    m_desc     = desc;
    m_heapType = heapType;

    D3D12_RESOURCE_STATES createState = initState;
    if (desc.Dimension == D3D12_RESOURCE_DIMENSION_BUFFER) {
        if (heapType == D3D12_HEAP_TYPE_UPLOAD)
            createState = D3D12_RESOURCE_STATE_GENERIC_READ;
        else if (heapType == D3D12_HEAP_TYPE_READBACK)
            createState = D3D12_RESOURCE_STATE_COPY_DEST;
        else
            createState = D3D12_RESOURCE_STATE_COMMON;
    }

    const auto hp = dx12::HeapProps(heapType);
    HRESULT hr = ctx->Device()->CreateCommittedResource(
        &hp, D3D12_HEAP_FLAG_NONE, &desc, createState, optClear,
        IID_PPV_ARGS(m_res.GetAddressOf()));
    if (FAILED(hr)) {
        if (ctx->NoteDeviceRemoved(hr, "CreateCommittedResource")) return hr;
        DXLOG_HR(hr, "[dx12] CreateCommittedResource %llux%u fmt=%d mips=%u "
                     "array=%u samples=%u flags=0x%X heap=%d layout=%d "
                     "align=%llu state=0x%X clear=%s",
                 (unsigned long long)desc.Width, desc.Height, (int)desc.Format,
                 desc.MipLevels, desc.DepthOrArraySize, desc.SampleDesc.Count,
                 (unsigned)desc.Flags, (int)heapType, (int)desc.Layout,
                 (unsigned long long)desc.Alignment, (unsigned)createState,
                 optClear ? "yes" : "no");

        // The same descriptor succeeds on one machine and fails on another, so
        // the HRESULT alone has never been enough to act on a field report.
        // Device state and both memory budgets are what separate "we asked for
        // something illegal" from "there was nothing left to give".
        if (const HRESULT removed = ctx->Device()->GetDeviceRemovedReason();
            removed != S_OK) {
            DXLOG_HR(removed, "[dx12] the device was already removed when this "
                              "resource was requested");
        }
        ctx->ReportMemoryState("resource creation failed");
        return hr;
    }
    if (debugName) m_res->SetName(debugName);

    m_planeCount = 1;
    if (desc.Dimension == D3D12_RESOURCE_DIMENSION_TEXTURE2D) {
        D3D12_FEATURE_DATA_FORMAT_INFO fi{ desc.Format, 0 };
        if (SUCCEEDED(ctx->Device()->CheckFeatureSupport(
                D3D12_FEATURE_FORMAT_INFO, &fi, sizeof(fi))) && fi.PlaneCount > 0)
            m_planeCount = fi.PlaneCount;
    }

    const UINT arraySize = (desc.Dimension == D3D12_RESOURCE_DIMENSION_TEXTURE3D)
                         ? 1u : UINT(desc.DepthOrArraySize);
    m_subCount = (desc.Dimension == D3D12_RESOURCE_DIMENSION_BUFFER)
               ? 1u
               : UINT(desc.MipLevels) * arraySize * m_planeCount;
    if (m_subCount == 0) m_subCount = 1;

    m_uniform      = true;
    m_uniformState = createState;
    m_states.clear();

    if (heapType == D3D12_HEAP_TYPE_UPLOAD) {
        D3D12_RANGE noRead{ 0, 0 };
        if (FAILED(m_res->Map(0, &noRead, reinterpret_cast<void**>(&m_mapped))))
            m_mapped = nullptr;
    }
    return S_OK;
}

void Resource12::Adopt(DeviceContext12* ctx, ID3D12Resource* res,
                       D3D12_RESOURCE_STATES initState,
                       int backBufferIndex) noexcept
{
    m_mirrorBackBuffer = backBufferIndex;
    m_ctx  = ctx;
    m_res  = res;
    if (res) m_desc = res->GetDesc();
    m_heapType     = D3D12_HEAP_TYPE_DEFAULT;
    m_planeCount   = 1;
    m_subCount     = 1;
    m_uniform      = true;
    m_uniformState = initState;
    m_states.clear();
    m_mapped = nullptr;
}

Resource12::~Resource12()
{
    Shutdown();
}

void Resource12::Shutdown() noexcept
{
    // The state journal holds raw pointers for the duration of one command
    // list; a resource the game releases mid-frame must not leave one behind.
    if (m_ctx) m_ctx->ForgetInStateJournal(this);
    if (m_mapped && m_res) {
        D3D12_RANGE noWrite{ 0, 0 };
        m_res->Unmap(0, &noWrite);
        m_mapped = nullptr;
    }
    ReleaseToRetirement();

    // Cleared last, and only after the two calls above have used it. A second
    // Shutdown, or the destructor running after one, then does nothing --
    // which is the point: the owner calls this while the context is alive, and
    // the destructor must not reach a context that has since been deleted.
    m_ctx      = nullptr;
    m_subCount = 0;
    m_uniform  = true;
    m_states.clear();
}

void Resource12::ReleaseToRetirement() noexcept
{

    if (m_res && m_ctx)
        m_ctx->Retire(m_res.Get());
    m_res.Reset();
}

void Resource12::Split() noexcept
{
    if (!m_uniform) return;
    m_states.assign(m_subCount, m_uniformState);
    m_uniform = false;
}

void Resource12::RestoreState(UINT sub, D3D12_RESOURCE_STATES state) noexcept
{
    if (sub == D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES) {
        m_uniform      = true;
        m_uniformState = state;
        m_states.clear();
        MirrorBackBufferState();
        return;
    }
    if (sub >= m_subCount) return;
    if (m_uniform) Split();
    if (sub < m_states.size()) m_states[sub] = state;
    MirrorBackBufferState();
}

D3D12_RESOURCE_STATES Resource12::StateOf(UINT sub) const noexcept
{
    if (m_uniform) return m_uniformState;
    return sub < m_states.size() ? m_states[sub] : m_uniformState;
}

void Resource12::MirrorBackBufferState() noexcept
{
    if (m_mirrorBackBuffer < 0 || !m_ctx) return;
    m_ctx->SetBackBufferState(static_cast<UINT>(m_mirrorBackBuffer),
                              StateOf(0));
}

void Resource12::OverrideState(UINT sub, D3D12_RESOURCE_STATES state) noexcept
{
    if (sub == D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES) {
        m_uniform      = true;
        m_uniformState = state;
        m_states.clear();
        MirrorBackBufferState();
        return;
    }
    Split();
    if (sub < m_states.size()) m_states[sub] = state;
    MirrorBackBufferState();
}

// Whether D3D12 will accept a transition of this resource to `after` at all.
//
// A rejected ResourceBarrier does not fail at the call. It poisons the command
// list, Close then returns E_INVALIDARG, and if that list is submitted anyway
// the device is removed. So an illegal transition has to be refused here, where
// the resource is still identifiable, rather than discovered three symptoms
// later with nothing naming the resource involved.
bool Resource12::CanTransitionTo(D3D12_RESOURCE_STATES after) const noexcept
{
    // Resources on the UPLOAD and READBACK heaps have one permanent state each
    // and cannot be transitioned out of it -- D3D12 rejects the barrier
    // outright. This is the rule a dynamic D3DPOOL_DEFAULT vertex or index
    // buffer runs into: ClassifyPlacement puts it on the UPLOAD heap, and the
    // draw path then asked for VERTEX_AND_CONSTANT_BUFFER on every draw that
    // used it. Being already in GENERIC_READ, it needs no barrier at all.
    if (m_heapType == D3D12_HEAP_TYPE_UPLOAD || m_heapType == D3D12_HEAP_TYPE_READBACK)
        return false;

    const D3D12_RESOURCE_FLAGS flags = m_desc.Flags;
    const char* why = nullptr;

    if ((after & D3D12_RESOURCE_STATE_RENDER_TARGET) &&
        !(flags & D3D12_RESOURCE_FLAG_ALLOW_RENDER_TARGET))
        why = "RENDER_TARGET without ALLOW_RENDER_TARGET";
    else if ((after & (D3D12_RESOURCE_STATE_DEPTH_WRITE | D3D12_RESOURCE_STATE_DEPTH_READ)) &&
             !(flags & D3D12_RESOURCE_FLAG_ALLOW_DEPTH_STENCIL))
        why = "DEPTH_WRITE/DEPTH_READ without ALLOW_DEPTH_STENCIL";
    else if ((after & D3D12_RESOURCE_STATE_UNORDERED_ACCESS) &&
             !(flags & D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS))
        why = "UNORDERED_ACCESS without ALLOW_UNORDERED_ACCESS";
    else if ((after & (D3D12_RESOURCE_STATE_PIXEL_SHADER_RESOURCE |
                       D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE)) &&
             (flags & D3D12_RESOURCE_FLAG_DENY_SHADER_RESOURCE))
        why = "shader-resource state on a DENY_SHADER_RESOURCE resource";

    if (!why) return true;

    static unsigned s_reported = 0;
    if (s_reported < 8u) {
        ++s_reported;
        DXLOG_ERROR("[dx12] refusing an illegal resource barrier: %s. Resource "
                    "%llux%u fmt=%d flags=0x%X, requested state 0x%X. The barrier "
                    "is being skipped; recording it would poison the command list "
                    "and remove the device.",
                    why, (unsigned long long)m_desc.Width, m_desc.Height,
                    (int)m_desc.Format, (unsigned)flags, (unsigned)after);
    }
    return false;
}

void Resource12::AppendTransition(std::vector<D3D12_RESOURCE_BARRIER>& out,
                                  UINT sub, D3D12_RESOURCE_STATES after) noexcept
{
    if (!m_res) return;
    if (!CanTransitionTo(after)) return;

    if (sub == D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES) {
        if (m_uniform) {
            if (m_uniformState == after) return;
            out.push_back(dx12::TransitionBarrier(
                m_res.Get(), m_uniformState, after,
                D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES));
            if (m_ctx) m_ctx->JournalState(this, sub, m_uniformState);
            m_uniformState = after;
            MirrorBackBufferState();
            return;
        }

        for (UINT i = 0; i < m_subCount; ++i) {
            if (m_states[i] == after) continue;
            out.push_back(dx12::TransitionBarrier(m_res.Get(), m_states[i], after, i));
            if (m_ctx) m_ctx->JournalState(this, i, m_states[i]);
        }
        m_uniform      = true;
        m_uniformState = after;
        m_states.clear();
        MirrorBackBufferState();
        return;
    }

    if (sub >= m_subCount) return;

    if (m_uniform) {
        if (m_uniformState == after) return;

        Split();
    }
    if (m_states[sub] == after) return;
    out.push_back(dx12::TransitionBarrier(m_res.Get(), m_states[sub], after, sub));
    if (m_ctx) m_ctx->JournalState(this, sub, m_states[sub]);
    m_states[sub] = after;
    MirrorBackBufferState();
}

void Resource12::AppendTransitionPlanes(std::vector<D3D12_RESOURCE_BARRIER>& out,
                                        UINT sub, D3D12_RESOURCE_STATES after) noexcept
{
    if (m_planeCount <= 1 || sub == D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES) {
        AppendTransition(out, sub, after);
        return;
    }

    // A depth-stencil format is two planes -- D24S8 becomes R24G8_TYPELESS with
    // depth in plane 0 and stencil in plane 1 -- and a DSV covers both. A caller
    // holding a mip/slice index has only named plane 0, so transitioning that
    // alone left the stencil plane wherever it happened to be, and the debug
    // layer rejected the clear naming "subresource: 1". Planes are the outermost
    // dimension of the subresource index, so the sibling planes are a fixed
    // stride away.
    const UINT arraySize = (m_desc.Dimension == D3D12_RESOURCE_DIMENSION_TEXTURE3D)
                         ? 1u : UINT(m_desc.DepthOrArraySize);
    const UINT planeStride = UINT(m_desc.MipLevels) * (arraySize ? arraySize : 1u);
    const UINT base = sub % (planeStride ? planeStride : 1u);

    for (UINT p = 0; p < m_planeCount; ++p)
        AppendTransition(out, base + p * planeStride, after);
}

void Resource12::Transition(ID3D12GraphicsCommandList* cmd, UINT sub,
                            D3D12_RESOURCE_STATES after) noexcept
{
    if (!cmd) return;
    std::vector<D3D12_RESOURCE_BARRIER> barriers;
    AppendTransition(barriers, sub, after);
    if (!barriers.empty())
        cmd->ResourceBarrier(static_cast<UINT>(barriers.size()), barriers.data());
}

void Resource12::GetFootprint(UINT sub,
                              D3D12_PLACED_SUBRESOURCE_FOOTPRINT* outFootprint,
                              UINT* outNumRows, UINT64* outRowSizeBytes,
                              UINT64* outTotalBytes) const noexcept
{
    if (!m_ctx || !m_ctx->Device()) return;
    m_ctx->Device()->GetCopyableFootprints(&m_desc, sub, 1, 0,
                                           outFootprint, outNumRows,
                                           outRowSizeBytes, outTotalBytes);
}

HRESULT Resource12::UploadSubresource(UINT sub, const void* src,
                                      UINT srcRowPitch, UINT srcSlicePitch) noexcept
{
    if (!m_res || !m_ctx || !src) return E_INVALIDARG;

    D3D12_PLACED_SUBRESOURCE_FOOTPRINT fp{};
    UINT   numRows      = 0;
    UINT64 rowSizeBytes = 0;
    UINT64 totalBytes   = 0;
    GetFootprint(sub, &fp, &numRows, &rowSizeBytes, &totalBytes);
    if (totalBytes == 0) return E_FAIL;

    auto alloc = m_ctx->AllocUpload(totalBytes, dx12::kTexPlaceAlign);
    if (!alloc.Valid()) return E_OUTOFMEMORY;

    const UINT depth = fp.Footprint.Depth ? fp.Footprint.Depth : 1;
    const auto copyRow = static_cast<size_t>(
        std::min<UINT64>(rowSizeBytes, srcRowPitch ? srcRowPitch : rowSizeBytes));
    for (UINT z = 0; z < depth; ++z) {
        const auto* srcSlice = static_cast<const uint8_t*>(src)
                             + size_t(z) * (srcSlicePitch ? srcSlicePitch
                                                          : srcRowPitch * numRows);
        uint8_t* dstSlice = alloc.cpu + size_t(z) * fp.Footprint.RowPitch * numRows;
        for (UINT y = 0; y < numRows; ++y)
            std::memcpy(dstSlice + size_t(y) * fp.Footprint.RowPitch,
                        srcSlice + size_t(y) * srcRowPitch,
                        copyRow);
    }

    auto* cmd = m_ctx->CmdList();
    if (!cmd) return E_FAIL;

    std::vector<D3D12_RESOURCE_BARRIER> barriers;
    AppendTransition(barriers, sub, D3D12_RESOURCE_STATE_COPY_DEST);
    if (!barriers.empty())
        cmd->ResourceBarrier(static_cast<UINT>(barriers.size()), barriers.data());

    if (m_desc.Dimension == D3D12_RESOURCE_DIMENSION_BUFFER) {
        cmd->CopyBufferRegion(m_res.Get(), 0, alloc.resource, alloc.offset,
                              std::min<UINT64>(totalBytes, m_desc.Width));
    } else {
        D3D12_TEXTURE_COPY_LOCATION dst{};
        dst.pResource        = m_res.Get();
        dst.Type             = D3D12_TEXTURE_COPY_TYPE_SUBRESOURCE_INDEX;
        dst.SubresourceIndex = sub;

        D3D12_TEXTURE_COPY_LOCATION srcLoc{};
        srcLoc.pResource       = alloc.resource;
        srcLoc.Type            = D3D12_TEXTURE_COPY_TYPE_PLACED_FOOTPRINT;
        srcLoc.PlacedFootprint = fp;
        srcLoc.PlacedFootprint.Offset = alloc.offset;

        cmd->CopyTextureRegion(&dst, 0, 0, 0, &srcLoc, nullptr);
    }
    return S_OK;
}

HRESULT Resource12::UploadSubresourceRegion(UINT sub,
                                            UINT dstX, UINT dstY, UINT dstZ,
                                            UINT width, UINT height, UINT depth,
                                            const void* src, UINT srcRowPitch,
                                            UINT srcSlicePitch) noexcept
{
    if (!m_res || !m_ctx || !src || width == 0 || height == 0) return E_INVALIDARG;
    if (m_desc.Dimension == D3D12_RESOURCE_DIMENSION_BUFFER)
        return UploadSubresource(sub, src, srcRowPitch, srcSlicePitch);
    if (depth == 0) depth = 1;

    D3D12_PLACED_SUBRESOURCE_FOOTPRINT full{};
    UINT   numRowsFull = 0;
    UINT64 rowSizeFull = 0, totalFull = 0;
    GetFootprint(sub, &full, &numRowsFull, &rowSizeFull, &totalFull);
    if (totalFull == 0) return E_FAIL;

    const UINT fullWidth = full.Footprint.Width ? full.Footprint.Width : 1;
    const UINT64 regionRowBytes =
        (rowSizeFull * width + fullWidth - 1) / fullWidth;
    const UINT rowPitch =
        dx12::AlignUp<UINT>(static_cast<UINT>(regionRowBytes), dx12::kTexRowAlign);
    const UINT rowsInRegion =
        (full.Footprint.Height && height > full.Footprint.Height)
            ? full.Footprint.Height
            : ((numRowsFull && full.Footprint.Height)
                   ? (numRowsFull * height + full.Footprint.Height - 1) / full.Footprint.Height
                   : height);

    const UINT64 totalBytes = UINT64(rowPitch) * rowsInRegion * depth;
    auto alloc = m_ctx->AllocUpload(totalBytes, dx12::kTexPlaceAlign);
    if (!alloc.Valid()) return E_OUTOFMEMORY;

    const size_t copyRow = static_cast<size_t>(
        std::min<UINT64>(regionRowBytes, srcRowPitch ? srcRowPitch : regionRowBytes));
    for (UINT z = 0; z < depth; ++z) {
        const auto* s = static_cast<const uint8_t*>(src)
                      + size_t(z) * (srcSlicePitch ? srcSlicePitch
                                                   : srcRowPitch * rowsInRegion);
        uint8_t* d = alloc.cpu + size_t(z) * rowPitch * rowsInRegion;
        for (UINT y = 0; y < rowsInRegion; ++y)
            std::memcpy(d + size_t(y) * rowPitch, s + size_t(y) * srcRowPitch, copyRow);
    }

    auto* cmd = m_ctx->CmdList();
    if (!cmd) return E_FAIL;

    std::vector<D3D12_RESOURCE_BARRIER> barriers;
    AppendTransition(barriers, sub, D3D12_RESOURCE_STATE_COPY_DEST);
    if (!barriers.empty())
        cmd->ResourceBarrier(static_cast<UINT>(barriers.size()), barriers.data());

    D3D12_TEXTURE_COPY_LOCATION dst{};
    dst.pResource        = m_res.Get();
    dst.Type             = D3D12_TEXTURE_COPY_TYPE_SUBRESOURCE_INDEX;
    dst.SubresourceIndex = sub;

    D3D12_TEXTURE_COPY_LOCATION srcLoc{};
    srcLoc.pResource                     = alloc.resource;
    srcLoc.Type                          = D3D12_TEXTURE_COPY_TYPE_PLACED_FOOTPRINT;
    srcLoc.PlacedFootprint.Offset        = alloc.offset;
    srcLoc.PlacedFootprint.Footprint.Format   = full.Footprint.Format;
    srcLoc.PlacedFootprint.Footprint.Width    = width;
    srcLoc.PlacedFootprint.Footprint.Height   = height;
    srcLoc.PlacedFootprint.Footprint.Depth    = depth;
    srcLoc.PlacedFootprint.Footprint.RowPitch = rowPitch;

    cmd->CopyTextureRegion(&dst, dstX, dstY, dstZ, &srcLoc, nullptr);
    return S_OK;
}

HRESULT Resource12::UploadBufferRange(UINT64 dstOffset, UINT64 bytes,
                                      const void* src) noexcept
{
    if (!m_res || !m_ctx || !src) return E_INVALIDARG;
    if (m_desc.Dimension != D3D12_RESOURCE_DIMENSION_BUFFER) return E_INVALIDARG;
    if (bytes == 0) return D3D_OK;
    if (dstOffset >= m_desc.Width) return E_INVALIDARG;
    bytes = std::min<UINT64>(bytes, m_desc.Width - dstOffset);

    auto alloc = m_ctx->AllocUpload(bytes, 16);
    if (!alloc.Valid()) return E_OUTOFMEMORY;
    std::memcpy(alloc.cpu, src, static_cast<size_t>(bytes));

    auto* cmd = m_ctx->CmdList();
    if (!cmd) return E_FAIL;

    std::vector<D3D12_RESOURCE_BARRIER> barriers;
    AppendTransition(barriers, 0, D3D12_RESOURCE_STATE_COPY_DEST);
    if (!barriers.empty())
        cmd->ResourceBarrier(static_cast<UINT>(barriers.size()), barriers.data());

    cmd->CopyBufferRegion(m_res.Get(), dstOffset, alloc.resource, alloc.offset, bytes);
    return S_OK;
}

HRESULT Resource12::ReadbackSubresource(UINT sub, void* dst,
                                        UINT dstRowPitch, UINT dstSlicePitch) noexcept
{
    if (!m_res || !m_ctx || !dst) return E_INVALIDARG;

    D3D12_PLACED_SUBRESOURCE_FOOTPRINT fp{};
    UINT   numRows    = 0;
    UINT64 rowSize    = 0;
    UINT64 totalBytes = 0;
    GetFootprint(sub, &fp, &numRows, &rowSize, &totalBytes);
    if (totalBytes == 0) return E_FAIL;

    const auto hp = dx12::HeapProps(D3D12_HEAP_TYPE_READBACK);
    const auto rd = dx12::BufferDesc(totalBytes);
    ComPtr<ID3D12Resource> readback;
    HRESULT hr = m_ctx->Device()->CreateCommittedResource(
        &hp, D3D12_HEAP_FLAG_NONE, &rd, D3D12_RESOURCE_STATE_COPY_DEST,
        nullptr, IID_PPV_ARGS(readback.GetAddressOf()));
    if (FAILED(hr)) {
        if (m_ctx->NoteDeviceRemoved(hr, "readback buffer allocation")) return hr;
        DXLOG_HR(hr, "[dx12] readback buffer (%llu bytes) allocation failed",
                 (unsigned long long)totalBytes);
        return hr;
    }

    auto* cmd = m_ctx->CmdList();
    if (!cmd) return E_FAIL;

    std::vector<D3D12_RESOURCE_BARRIER> barriers;
    AppendTransition(barriers, sub, D3D12_RESOURCE_STATE_COPY_SOURCE);
    if (!barriers.empty())
        cmd->ResourceBarrier(static_cast<UINT>(barriers.size()), barriers.data());

    if (m_desc.Dimension == D3D12_RESOURCE_DIMENSION_BUFFER) {
        cmd->CopyBufferRegion(readback.Get(), 0, m_res.Get(), 0, totalBytes);
    } else {
        D3D12_TEXTURE_COPY_LOCATION dstLoc{};
        dstLoc.pResource                = readback.Get();
        dstLoc.Type                     = D3D12_TEXTURE_COPY_TYPE_PLACED_FOOTPRINT;
        dstLoc.PlacedFootprint          = fp;
        dstLoc.PlacedFootprint.Offset   = 0;

        D3D12_TEXTURE_COPY_LOCATION srcLoc{};
        srcLoc.pResource        = m_res.Get();
        srcLoc.Type             = D3D12_TEXTURE_COPY_TYPE_SUBRESOURCE_INDEX;
        srcLoc.SubresourceIndex = sub;

        cmd->CopyTextureRegion(&dstLoc, 0, 0, 0, &srcLoc, nullptr);
    }

    hr = m_ctx->FlushAndWait();
    if (FAILED(hr)) return hr;

    uint8_t* mapped = nullptr;
    D3D12_RANGE readRange{ 0, static_cast<SIZE_T>(totalBytes) };
    hr = readback->Map(0, &readRange, reinterpret_cast<void**>(&mapped));
    if (FAILED(hr)) return hr;

    const UINT depth = fp.Footprint.Depth ? fp.Footprint.Depth : 1;
    const size_t copyRow = static_cast<size_t>(
        std::min<UINT64>(rowSize, dstRowPitch ? dstRowPitch : rowSize));
    for (UINT z = 0; z < depth; ++z) {
        const uint8_t* s = mapped + size_t(z) * fp.Footprint.RowPitch * numRows;
        auto* d = static_cast<uint8_t*>(dst)
                + size_t(z) * (dstSlicePitch ? dstSlicePitch : dstRowPitch * numRows);
        for (UINT y = 0; y < numRows; ++y)
            std::memcpy(d + size_t(y) * dstRowPitch,
                        s + size_t(y) * fp.Footprint.RowPitch, copyRow);
    }

    D3D12_RANGE noWrite{ 0, 0 };
    readback->Unmap(0, &noWrite);
    return S_OK;
}

HRESULT Resource12::CopySubresourceFrom(Resource12& src, UINT srcSub, UINT dstSub,
                                        const D3D12_BOX* srcBox,
                                        UINT dstX, UINT dstY, UINT dstZ) noexcept
{
    if (!m_res || !src.m_res || !m_ctx) return E_INVALIDARG;
    auto* cmd = m_ctx->CmdList();
    if (!cmd) return E_FAIL;

    std::vector<D3D12_RESOURCE_BARRIER> barriers;
    src.AppendTransition(barriers, srcSub, D3D12_RESOURCE_STATE_COPY_SOURCE);
    AppendTransition(barriers, dstSub, D3D12_RESOURCE_STATE_COPY_DEST);
    if (!barriers.empty())
        cmd->ResourceBarrier(static_cast<UINT>(barriers.size()), barriers.data());

    if (m_desc.Dimension == D3D12_RESOURCE_DIMENSION_BUFFER &&
        src.m_desc.Dimension == D3D12_RESOURCE_DIMENSION_BUFFER) {
        const UINT64 bytes = srcBox ? (srcBox->right - srcBox->left)
                                    : std::min(m_desc.Width, src.m_desc.Width);
        cmd->CopyBufferRegion(m_res.Get(), dstX, src.m_res.Get(),
                              srcBox ? srcBox->left : 0, bytes);
        return S_OK;
    }

    D3D12_TEXTURE_COPY_LOCATION d{};
    d.pResource        = m_res.Get();
    d.Type             = D3D12_TEXTURE_COPY_TYPE_SUBRESOURCE_INDEX;
    d.SubresourceIndex = dstSub;

    D3D12_TEXTURE_COPY_LOCATION s{};
    s.pResource        = src.m_res.Get();
    s.Type             = D3D12_TEXTURE_COPY_TYPE_SUBRESOURCE_INDEX;
    s.SubresourceIndex = srcSub;

    cmd->CopyTextureRegion(&d, dstX, dstY, dstZ, &s, srcBox);
    return S_OK;
}

}
